### PR TITLE
Josephreddy #issue9

### LINKED ISSUE #9: ISSUE-9 As a user, I want to add solid blue blocks grouped together to represent water, in order to make the terrain more diverse.
Definition of done:
- Groups of blue blocks appear in game in groups of 5 or more and are connected to the ground.
- Frequency and appearing accurate not important at this stage.

### PR DESCRIPTION
**Pull request by josephreddyyeruva**
sorry guys I did a mistake in the previous pull request. please give me the review for this.

### CODE REVIEW

**Review by j2quik — CHANGES_REQUESTED** [review]
The function comments for Terrain.py look good.
I don't understand the test cases for Terrain.py. There are tests for classes and functions that are not in the Terrain.py source code file. Did you get some files confused?

**Comment by josephreddyyeruva** [comment]
> The function comments for Terrain.py look good.
> I don't understand the test cases for Terrain.py. There are tests for classes and functions that are not in the Terrain.py source code file. Did you get some files confused?

yeah. I did a mistake there. I have corrected it now. u can review it now.

**Review by j2quik — COMMENTED** [review]
Maybe it's late and I'm missing something here, but Terrain.py only has 1 function add_water(). I still see test cases for functions not in Terrain.py and none for add_water(). Is this correct?

**Comment by josephreddyyeruva** [comment]
> Maybe it's late and I'm missing something here, but Terrain.py only has 1 function add_water(). I still see test cases for functions not in Terrain.py and none for add_water(). Is this correct?

I have made the changes.

**Review by j2quik — APPROVED** [review]
Test case implementation looks good and passed.

**Pull request merged**
